#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# -----------------------------------------------------------------------
# Generates the Postgres credentials that docker/.env intentionally ships
# empty, so that no stack is ever provisioned with a well-known password.
#
# Values are written to docker/.env-local (git-ignored), which docker
# compose loads after docker/.env. Existing values are never overwritten,
# so the script is safe to run before every `up`.
#
# Usage:
#   ./scripts/generate-docker-secrets.sh
# -----------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_LOCAL="$REPO_ROOT/docker/.env-local"

random_secret() {
    openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | cut -c1-24
}

# Echoes the value already configured for $1, either in the environment or
# in docker/.env-local; empty when the variable still needs a value.
existing_value() {
    local var_name=$1
    if [ -n "${!var_name:-}" ]; then
        echo "${!var_name}"
    elif [ -f "$ENV_LOCAL" ]; then
        sed -nE "s/^[[:space:]]*${var_name}=(.+)$/\1/p" "$ENV_LOCAL" | tail -1
    fi
}

append_var() {
    if [ ! -f "$ENV_LOCAL" ]; then
        echo "# Generated by scripts/generate-docker-secrets.sh" > "$ENV_LOCAL"
    fi
    echo "$1=$2" >> "$ENV_LOCAL"
    echo "🔐 Generated $1 in docker/.env-local"
}

# The metadata DB password must match the superuser password Postgres is
# provisioned with, so both variables share a single generated value.
db_password=$(existing_value DATABASE_PASSWORD)
postgres_password=$(existing_value POSTGRES_PASSWORD)
if [ -z "$db_password" ] && [ -z "$postgres_password" ]; then
    db_password=$(random_secret)
    append_var DATABASE_PASSWORD "$db_password"
    append_var POSTGRES_PASSWORD "$db_password"
elif [ -z "$db_password" ]; then
    append_var DATABASE_PASSWORD "$postgres_password"
elif [ -z "$postgres_password" ]; then
    append_var POSTGRES_PASSWORD "$db_password"
fi

if [ -z "$(existing_value EXAMPLES_PASSWORD)" ]; then
    append_var EXAMPLES_PASSWORD "$(random_secret)"
fi
